model_select: "pcnn"
#gcn, gin, egat,gat, gnn, rbf_gat,transformer,dimenet,pcnn
select_dataset: "qm9"
force_field: 'uff'
#mmff,uff,random
#qm8,qm9
tras_med: 'hl'
#hl,lh,hllh,lhhl,hl-lh
#
#[2,3,4]
#qm8:{'E1-CC2':0,'E2-CC2':1,'f1-CC2':2,'f2-CC2':3,'E1-PBE0':4,'E2-PBE0':5,'f1-PBE0':6,'f2-PBE0':7,'E1-CAM':8,'E2-CAM':9,'f1-CAM':10,'f2-CAM':11,'all':12}
#
#qm9:{'mu':0,'alpha':1,'homo':2,'lumo':3,'gap':4,'r2':5,'zpve':6,'u0':7,'u298':8,'h298':9,'g298':10,'cv':11,'u0_atom':12,'u298_atom':13,'h298_atom':14,'g298_atom':15}
#u0,u298,h298,g298
encoder_atom: "cgcnn"
#encoder_method = ("atomic_number":1, "basic":11, "cfid":438, "cgcnn":92,'self':62,'gme':140)
encoder_bond: "dim_14"
#encoder_method = ("dim_14":14, "dim_26":26)
encode_two_path: "dim_8"
#encode_two_path: {"dim_e":8,"dim_10":10}
encode_tree_path: "dim_6"
#encode_tree_path={"dim_s":6,"dim_15":15}
head: 6
layer_number: 2
num_blcok: 1
resent: False
#Ture,False,
pooling: "avg"
#glob,sort,avg
loss_sclect: 'l1'
#l1,l2
LR: 0.001
NUM_EPOCHS: 501
batch_size: 64
train_ratio: 0.8
vali_ratio: 0.1
test_ratio: 0.1
iter: 5
